spring:
  neo4j:
    authentication:
      username: neo4j
      password: letmein!
    uri: bolt://localhost:7687
  datasource:
    driver-class-name: liquibase.ext.neo4j.database.jdbc.Neo4jDriver
    url: jdbc:neo4j:${spring.neo4j.uri}
    username: ${spring.neo4j.authentication.username}
    password: ${spring.neo4j.authentication.password}
debug: true
